
# The log file location
log:
filename: "food-calc.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  # stage: ""
  # prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - User
    - Ta
    - Student
    - Question
    - Course
    - TaCRelation
    - SCRelation
